version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  blacklist_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${BLACKLIST_DB_USER}
      POSTGRES_PASSWORD: ${BLACKLIST_DB_PASSWORD}
      POSTGRES_DB: ${BLACKLIST_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata_blacklist:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db
      - blacklist_db

volumes:
  pgdata:
  pgdata_blacklist:
